spring:
  application:
    name: BusTime_backend
  config:
    import: optional:file:.env[.properties]

  cache:
    type: redis
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

  cache.redis.time-to-live: 30s

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never

public-api:
  service-key: ${PUBLIC_API_SERVICE_KEY}